### ISSUE TITLE
BUG ： QPixmap::scaled: Pixmap is a null pixmap

### ISSUE THREAD

**Issue by youyuge34** [afunTW/pyqt5-binary-classifier#2]
ln line 29 in app.py, the original `blob` func was a wrong way to list images, due to there is no `*` in image-dir parameter.
Corrected: `self.image_paths = [os.path.join(imgdir,x) for x in os.listdir(imgdir)]`

**Comment by afunTW** [comment]
@youyuge34 thanks your report

First of all, thanks for your report, I have never thought about someone who will use this.
Second, since the tool built when I am an amateur programmer, the logic is not concrete and intuitive.

What I am doing here is input the `*` in cli, `imgdir` accepts the patten
e.g.
```
python3 main.py --img-dir ~/data/*.png
``` 

If we want to make this better, it's better to plugin the file dialog and handles the file extension as well.
Welcome to contribute!
